/* Generated By:JavaCC: Do not edit this line. QueryParserConstants.java */
package de.mpg.escidoc.services.pubman.searching;

public interface QueryParserConstants {

  int EOF = 0;
  int AND = 4;
  int OR = 5;
  int NOT = 6;
  int QUOTED = 7;
  int SPECIAL = 8;
  int CONSTANT = 9;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"AND\"",
    "\"OR\"",
    "\"NOT\"",
    "<QUOTED>",
    "\"<\"",
    "<CONSTANT>",
    "\"(\"",
    "\")\"",
  };

}
