# pubman.properties template
inge.aa.instance.url=${inge.aa.instance.url}
inge.aa.default.target=${inge.aa.default.target}
inge.aa.private.key.file=${inge.aa.private.key.file}
inge.aa.public.key.file=${inge.aa.public.key.file}
inge.aa.client.class=${inge.aa.client.class}
inge.aa.client.start.class=${inge.aa.client.start.class}
inge.aa.client.finish.class=${inge.aa.client.finish.class}
inge.aa.client.logout.class=${inge.aa.client.logout.class}
inge.auth.mpg.ip.json.url=${inge.auth.mpg.ip.json.url}
inge.auth.mpg.ip.use=${inge.auth.mpg.ip.use}
inge.cone.cache.use=${inge.cone.cache.use}
inge.cone.database.driver.class=${inge.cone.database.driver.class}
inge.cone.database.name=${inge.cone.database.name}
inge.cone.database.server.name=${inge.cone.database.server.name}
inge.cone.database.server.port=${inge.cone.database.server.port}
inge.cone.database.user.name=${inge.cone.database.user.name}
inge.cone.database.user.password=${inge.cone.database.user.password}
inge.cone.language.default=${inge.cone.language.default}
inge.cone.modelsxml.path=${inge.cone.modelsxml.path}
inge.cone.person.id.identifier=${inge.cone.person.id.identifier}
inge.cone.querier.class=${inge.cone.querier.class}
inge.cone.rdfs.template=${inge.cone.rdfs.template}
inge.cone.results.default=${inge.cone.results.default}
inge.cone.results.maximum=${inge.cone.results.maximum}
inge.cone.service.url=${inge.cone.service.url}
inge.cron.cleanup_staging_files=${inge.cron.cleanup_staging_files}
inge.cron.cleanup_staging_files.hours=${inge.cron.cleanup_staging_files.hours}
inge.cron.fix_broken_imports=${inge.cron.fix_broken_imports}
inge.cron.fix_broken_imports.hours=${inge.cron.fix_broken_imports.hours}
inge.cron.init_ip_list=${inge.cron.init_ip_list}
inge.cron.init_search_index_fields=${inge.cron.init_search_index_fields}
inge.cron.pubman.sitemap=${inge.cron.pubman.sitemap}
inge.cron.refresh_cone_cache=${inge.cron.refresh_cone_cache}
inge.crossref.pid=${inge.crossref.pid}
inge.database.driver.class=${inge.database.driver.class}
inge.database.jdbc.url=${inge.database.jdbc.url}
inge.database.user.name=${inge.database.user.name}
inge.database.user.password=${inge.database.user.password}
inge.doi.service.create.url=${inge.doi.service.create.url}
inge.doi.service.password=${inge.doi.service.password}
inge.doi.service.url=${inge.doi.service.url}
inge.doi.service.use=${inge.doi.service.use}
inge.doi.service.user=${inge.doi.service.user}
inge.es.rest.host-port=${inge.es.rest.host-port}
inge.es.rest.path-prefix=${inge.es.rest.path-prefix}
inge.es.user=${inge.es.user}
inge.es.password=${inge.es.password}
inge.filestorage.seaweed_direct_submit_path=${inge.filestorage.seaweed_direct_submit_path}
inge.filestorage.seaweed_master_server_ip=${inge.filestorage.seaweed_master_server_ip}
inge.import.sources.xml=${inge.import.sources.xml}
inge.index.context.name=${inge.index.context.name}
inge.index.context.sort=${inge.index.context.sort}
inge.index.context.type=${inge.index.context.type}
inge.index.item.name=${inge.index.item.name}
inge.index.item.sort=${inge.index.item.sort}
inge.index.item.type=${inge.index.item.type}
inge.index.organization.name=${inge.index.organization.name}
inge.index.organization.sort=${inge.index.organization.sort}
inge.index.organization.type=${inge.index.organization.type}
inge.index.user.name=${inge.index.user.name}
inge.index.user.sort=${inge.index.user.sort}
inge.index.user.type=${inge.index.user.type}
inge.jwt.shared-secret=${inge.jwt.shared-secret}
inge.openai.model=${inge.openai.model}
inge.openai.prompt=${inge.openai.prompt}
inge.openai.temperature=${inge.openai.temperature}
inge.openai.token=${inge.openai.token}
inge.openai.url=${inge.openai.url}
inge.pid.handle.short=${inge.pid.handle.short}
inge.pid.handle.url=${inge.pid.handle.url}
inge.pid.service.create.path=${inge.pid.service.create.path}
inge.pid.service.password=${inge.pid.service.password}
inge.pid.service.timeout=${inge.pid.service.timeout}
inge.pid.service.url=${inge.pid.service.url}
inge.pid.service.use=${inge.pid.service.use}
inge.pid.service.user=${inge.pid.service.user}
inge.pubman.component.pattern=${inge.pubman.component.pattern}
inge.pubman.external.organization.id=${inge.pubman.external.organization.id}
inge.pubman.genres.configuration=${inge.pubman.genres.configuration}
inge.pubman.instance.context.path=${inge.pubman.instance.context.path}
inge.pubman.instance.url=${inge.pubman.instance.url}
inge.pubman.item.pattern=${inge.pubman.item.pattern}
inge.pubman.presentation.url=${inge.pubman.presentation.url}
inge.pubman.root.organization.id=${inge.pubman.root.organization.id}
inge.pubman.sitemap.max.items=${inge.pubman.sitemap.max.items}
inge.pubman.sitemap.retrieve.items=${inge.pubman.sitemap.retrieve.items}
inge.pubman.stylesheet.url=${inge.pubman.stylesheet.url}
inge.rest.api.description=${inge.rest.api.description}
inge.rest.service.url=${inge.rest.service.url}
inge.rest.development.admin.username=${inge.rest.development.admin.username}
inge.rest.development.admin.password=${inge.rest.development.admin.password}
inge.rest.development.enabled=${inge.rest.development.enabled}
inge.rest.development.file_url=${inge.rest.development.file_url}
inge.transformation.arxiv2escidoc_publication_component.stylesheet.filename = ${inge.transformation.arxiv2escidoc_publication_component.stylesheet.filename}
inge.transformation.arxiv2escidoc_publication_item.stylesheet.filename = ${inge.transformation.arxiv2escidoc_publication_item.stylesheet.filename}
inge.transformation.bibtex.configuration.filename = ${inge.transformation.bibtex.configuration.filename}
inge.transformation.bmc2escidoc.configuration.filename = ${inge.transformation.bmc2escidoc.configuration.filename}
inge.transformation.bmc2escidoc.stylesheet.filename = ${inge.transformation.bmc2escidoc.stylesheet.filename}
inge.transformation.bmc2escidoc_publication_component.stylesheet.filename = ${inge.transformation.bmc2escidoc_publication_component.stylesheet.filename}
inge.transformation.bmc2escidoc_publication_item.stylesheet.filename = ${inge.transformation.bmc2escidoc_publication_item.stylesheet.filename}
inge.transformation.bmc_fulltext_xml2bmc_fulltext_html.stylesheet.filename = ${inge.transformation.bmc_fulltext_xml2bmc_fulltext_html.stylesheet.filename}
inge.transformation.crossref2escidoc_publication_item.stylesheet.filename = ${inge.transformation.crossref2escidoc_publication_item.stylesheet.filename}
inge.transformation.doi.stylesheet.filename = ${inge.transformation.doi.stylesheet.filename}
inge.transformation.edoc.configuration.filename = ${inge.transformation.edoc.configuration.filename}
inge.transformation.edoc.stylesheet.filename = ${inge.transformation.edoc.stylesheet.filename}
inge.transformation.endnote.configuration.filename = ${inge.transformation.endnote.configuration.filename}
inge.transformation.endnote.ice.stylesheet.filename = ${inge.transformation.endnote.ice.stylesheet.filename}
inge.transformation.endnote.stylesheet.filename = ${inge.transformation.endnote.stylesheet.filename}
inge.transformation.escidoc.itemlist.to.snippet.stylesheet.filename = ${inge.transformation.escidoc.itemlist.to.snippet.stylesheet.filename}
inge.transformation.escidoc.snippet.to.html.stylesheet.filename = ${inge.transformation.escidoc.snippet.to.html.stylesheet.filename}
inge.transformation.escidoc2bibtex.stylesheet.filename = ${inge.transformation.escidoc2bibtex.stylesheet.filename}
inge.transformation.escidoc2edoc_export.stylesheet.filename = ${inge.transformation.escidoc2edoc_export.stylesheet.filename}
inge.transformation.escidoc2edoc_import.stylesheet.filename = ${inge.transformation.escidoc2edoc_import.stylesheet.filename}
inge.transformation.escidoc2endnote.stylesheet.filename = ${inge.transformation.escidoc2endnote.stylesheet.filename}
inge.transformation.escidoc2marcxml.stylesheet.filename = ${inge.transformation.escidoc2marcxml.stylesheet.filename}
inge.transformation.escidoc_v1_to_escidoc_v2.stylesheet.filename = ${inge.transformation.escidoc_v1_to_escidoc_v2.stylesheet.filename}
inge.transformation.escidoc_v2_to_escidoc_v1.stylesheet.filename = ${inge.transformation.escidoc_v2_to_escidoc_v1.stylesheet.filename}
inge.transformation.escidoc_v3_to_escidoc_v2.stylesheet.filename = ${inge.transformation.escidoc_v3_to_escidoc_v2.stylesheet.filename}
inge.transformation.html_metatags_dc.stylesheet.filename = ${inge.transformation.html_metatags_dc.stylesheet.filename}
inge.transformation.html_metatags_highwire.stylesheet.filename = ${inge.transformation.html_metatags_highwire.stylesheet.filename}
inge.transformation.jus_indesign.stylesheet.filename = ${inge.transformation.jus_indesign.stylesheet.filename}
inge.transformation.jus_snippet2jus.stylesheet.filename = ${inge.transformation.jus_snippet2jus.stylesheet.filename}
inge.transformation.mab.content.url.prefix = ${inge.transformation.mab.content.url.prefix}
inge.transformation.mab.stylesheet.filename = ${inge.transformation.mab.stylesheet.filename}
inge.transformation.marcxml2escidoc.configuration.filename = ${inge.transformation.marcxml2escidoc.configuration.filename}
inge.transformation.marcxml2escidoc.stylesheet.filename = ${inge.transformation.marcxml2escidoc.stylesheet.filename}
inge.transformation.mods2marc.stylesheet.filename = ${inge.transformation.mods2marc.stylesheet.filename}
inge.transformation.mods2oaidc.stylesheet.filename = ${inge.transformation.mods2oaidc.stylesheet.filename}
inge.transformation.mods_item.stylesheet.filename = ${inge.transformation.mods_item.stylesheet.filename}
inge.transformation.oai_dc.stylesheet.filename = ${inge.transformation.oai_dc.stylesheet.filename}
inge.transformation.peer.stylesheet.filename = ${inge.transformation.peer.stylesheet.filename}
inge.transformation.pmc2escidoc_publication_component.stylesheet.filename = ${inge.transformation.pmc2escidoc_publication_component.stylesheet.filename}
inge.transformation.pmc2escidoc_publication_item.stylesheet.filename = ${inge.transformation.pmc2escidoc_publication_item.stylesheet.filename}
inge.transformation.ris.configuration.filename = ${inge.transformation.ris.configuration.filename}
inge.transformation.ris.stylesheet.filename = ${inge.transformation.ris.stylesheet.filename}
inge.transformation.spires2escidoc_publication_item.stylesheet.filename = ${inge.transformation.spires2escidoc_publication_item.stylesheet.filename}
inge.transformation.wos.configuration.filename = ${inge.transformation.wos.configuration.filename}
inge.transformation.wos.stylesheet.filename = ${inge.transformation.wos.stylesheet.filename}
inge.transformation.zfn.configuration.filename = ${inge.transformation.zfn.configuration.filename}
inge.transformation.zfn.stylesheet.filename = ${inge.transformation.zfn.stylesheet.filename}
inge.rest.access-control-allowed-origins=${inge.rest.access-control-allowed-origins}
