CREATE TABLE escidoc_import_log (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    status character varying NOT NULL,
    errorlevel character varying NOT NULL,
    startdate timestamp NOT NULL,
    enddate timestamp,
    action character varying,
    userid character varying,
    name character varying,
    format character varying,
    context character varying,
    percentage integer
);

CREATE TABLE escidoc_import_log_detail (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    status character varying NOT NULL,
    errorlevel character varying NOT NULL,
    startdate timestamp NOT NULL,
    enddate timestamp,
    parent integer NOT NULL,
    message character varying,
    item_id character varying,
    action character varying
);

CREATE TABLE escidoc_import_log_item (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    status character varying NOT NULL,
    errorlevel character varying NOT NULL,
    startdate timestamp NOT NULL,
    enddate timestamp,
    parent integer NOT NULL,
    message character varying,
    item_id character varying,
    action character varying
);

